"""Add activity_logs table with unique constraint

Revision ID: 14d5a3bca78f
Revises: f3dc9da1438c
Create Date: 2025-08-04 17:57:53.046511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d5a3bca78f'
down_revision: Union[str, None] = 'f3dc9da1438c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=20), nullable=False),
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('student_input', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.Text(), nullable=True),
    sa.Column('third_eval_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['session_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'student_name', 'activity_key', 'turn_index', name='uq_activity_logs_run_student_activity_turn')
    )
    op.create_index(op.f('ix_activity_logs_activity_key'), 'activity_logs', ['activity_key'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_run_id'), 'activity_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_student_name'), 'activity_logs', ['student_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_student_name'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_run_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_key'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
