"""Add session_runs and join_codes tables for S3

Revision ID: 16184b03bbe8
Revises: 39d3476b643c
Create Date: 2025-08-03 13:08:41.893601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16184b03bbe8'
down_revision: Union[str, None] = '39d3476b643c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'LIVE', 'ENDED', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['session_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_runs_created_at', 'session_runs', ['created_at'], unique=False)
    op.create_index('idx_session_runs_status', 'session_runs', ['status'], unique=False)
    op.create_index('idx_session_runs_template_id', 'session_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_session_runs_id'), 'session_runs', ['id'], unique=False)
    op.create_index(op.f('ix_session_runs_status'), 'session_runs', ['status'], unique=False)
    op.create_index(op.f('ix_session_runs_template_id'), 'session_runs', ['template_id'], unique=False)
    op.create_table('join_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['session_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_join_codes_is_active', 'join_codes', ['is_active'], unique=False)
    op.create_index('idx_join_codes_run_id', 'join_codes', ['run_id'], unique=False)
    op.create_index('idx_join_codes_unique_active', 'join_codes', ['code'], unique=True, postgresql_where=sa.text('is_active = 1'), sqlite_where=sa.text('is_active = 1'))
    op.create_index(op.f('ix_join_codes_code'), 'join_codes', ['code'], unique=False)
    op.create_index(op.f('ix_join_codes_id'), 'join_codes', ['id'], unique=False)
    op.create_index(op.f('ix_join_codes_is_active'), 'join_codes', ['is_active'], unique=False)
    op.create_index(op.f('ix_join_codes_run_id'), 'join_codes', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_join_codes_run_id'), table_name='join_codes')
    op.drop_index(op.f('ix_join_codes_is_active'), table_name='join_codes')
    op.drop_index(op.f('ix_join_codes_id'), table_name='join_codes')
    op.drop_index(op.f('ix_join_codes_code'), table_name='join_codes')
    op.drop_index('idx_join_codes_unique_active', table_name='join_codes', postgresql_where=sa.text('is_active = 1'), sqlite_where=sa.text('is_active = 1'))
    op.drop_index('idx_join_codes_run_id', table_name='join_codes')
    op.drop_index('idx_join_codes_is_active', table_name='join_codes')
    op.drop_table('join_codes')
    op.drop_index(op.f('ix_session_runs_template_id'), table_name='session_runs')
    op.drop_index(op.f('ix_session_runs_status'), table_name='session_runs')
    op.drop_index(op.f('ix_session_runs_id'), table_name='session_runs')
    op.drop_index('idx_session_runs_template_id', table_name='session_runs')
    op.drop_index('idx_session_runs_status', table_name='session_runs')
    op.drop_index('idx_session_runs_created_at', table_name='session_runs')
    op.drop_table('session_runs')
    # ### end Alembic commands ###
