"""Add modes and session_templates tables

Revision ID: 39d3476b643c
Revises: 48ef972a9381
Create Date: 2025-08-03 00:59:30.504401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d3476b643c'
down_revision: Union[str, None] = '48ef972a9381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('options_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modes_id'), 'modes', ['id'], unique=False)
    op.create_table('session_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_templates_teacher_id', 'session_templates', ['teacher_id'], unique=False)
    op.create_index('idx_session_templates_title', 'session_templates', ['title'], unique=False)
    op.create_index(op.f('ix_session_templates_id'), 'session_templates', ['id'], unique=False)
    op.create_index(op.f('ix_session_templates_teacher_id'), 'session_templates', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_templates_teacher_id'), table_name='session_templates')
    op.drop_index(op.f('ix_session_templates_id'), table_name='session_templates')
    op.drop_index('idx_session_templates_title', table_name='session_templates')
    op.drop_index('idx_session_templates_teacher_id', table_name='session_templates')
    op.drop_table('session_templates')
    op.drop_index(op.f('ix_modes_id'), table_name='modes')
    op.drop_table('modes')
    # ### end Alembic commands ###
