"""Add name field to session_runs

Revision ID: a5b95a8e3bc2
Revises: 16184b03bbe8
Create Date: 2025-08-04 13:04:28.703212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b95a8e3bc2'
down_revision: Union[str, None] = '16184b03bbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기본값과 함께 nullable로 추가 (SQLite 호환)
    op.add_column('session_runs', sa.Column('name', sa.String(length=200), nullable=True, server_default=''))
    
    # 기존 레코드에 기본 이름 설정
    op.execute("UPDATE session_runs SET name = '세션 #' || id WHERE name IS NULL OR name = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_runs', 'name')
    # ### end Alembic commands ###
