"""Add enrollments table for student enrollment

Revision ID: f3dc9da1438c
Revises: a5b95a8e3bc2
Create Date: 2025-08-04 16:00:51.034280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dc9da1438c'
down_revision: Union[str, None] = 'a5b95a8e3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('normalized_student_name', sa.String(length=20), nullable=False),
    sa.Column('rejoin_pin_hash', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['session_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollments_unique_name_per_run', 'enrollments', ['run_id', 'normalized_student_name'], unique=True)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_run_id'), 'enrollments', ['run_id'], unique=False)
    # Note: SQLite does not support ALTER COLUMN, and name column should already exist from previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_run_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index('idx_enrollments_unique_name_per_run', table_name='enrollments')
    op.drop_table('enrollments')
    # Note: SQLite does not support ALTER COLUMN
    # ### end Alembic commands ###
